"""자주 쓰는 아이템의 한글 별칭 → 마인크래프트 아이템 ID 대응표.

[유지보수 안내 — 별칭 추가 방법]
- 키는 한글 별칭에서 "공백을 모두 뺀" 형태로 적습니다. 입력을 비교할 때도
  공백을 제거하므로 "다이아 검"과 "다이아검" 모두 같은 항목에 걸립니다.
- 값은 `minecraft:` 접두사를 뺀 소문자 아이템 ID입니다.
- 별칭에 없는 이름이라도 영어 아이템 ID(예: diamond, iron_sword)는 항상
  그대로 사용할 수 있습니다. 별칭은 편의 기능일 뿐입니다.
- 어떤 이름이 애매하면(예: "곡괭이"만으로는 재질을 모름) 추가하지 말고
  재질을 붙인 별칭만 둡니다.
"""

ITEM_ALIASES = {
    # ── 광물·재료 ─────────────────────────────────────────────
    "다이아": "diamond",
    "다이아몬드": "diamond",
    "에메랄드": "emerald",
    "철": "iron_ingot",
    "철괴": "iron_ingot",
    "금": "gold_ingot",
    "금괴": "gold_ingot",
    "구리": "copper_ingot",
    "구리괴": "copper_ingot",
    "네더라이트": "netherite_ingot",
    "네더라이트주괴": "netherite_ingot",
    "석탄": "coal",
    "청금석": "lapis_lazuli",
    "레드스톤": "redstone",
    "석영": "quartz",
    "자수정": "amethyst_shard",
    "막대기": "stick",
    "화약": "gunpowder",
    "실": "string",
    "가죽": "leather",
    "종이": "paper",
    "책": "book",
    "뼈": "bone",
    "뼛가루": "bone_meal",
    "슬라임볼": "slime_ball",
    "엔더진주": "ender_pearl",
    "진주": "ender_pearl",
    "엔더의눈": "ender_eye",
    "블레이즈막대": "blaze_rod",
    "네더의별": "nether_star",
    "발광석": "glowstone",
    "발광석가루": "glowstone_dust",
    "부싯돌": "flint",
    # ── 블록 ─────────────────────────────────────────────────
    "흙": "dirt",
    "잔디블록": "grass_block",
    "돌": "stone",
    "조약돌": "cobblestone",
    "모래": "sand",
    "자갈": "gravel",
    "유리": "glass",
    "참나무원목": "oak_log",
    "참나무판자": "oak_planks",
    "판자": "oak_planks",
    "횃불": "torch",
    "사다리": "ladder",
    "상자": "chest",
    "엔더상자": "ender_chest",
    "셜커상자": "shulker_box",
    "화로": "furnace",
    "제작대": "crafting_table",
    "침대": "red_bed",
    "흑요석": "obsidian",
    "티엔티": "tnt",
    "모루": "anvil",
    "마법부여대": "enchanting_table",
    "인챈트테이블": "enchanting_table",
    "신호기": "beacon",
    "다이아블록": "diamond_block",
    "철블록": "iron_block",
    "금블록": "gold_block",
    "에메랄드블록": "emerald_block",
    "관측기": "observer",
    "피스톤": "piston",
    "끈끈이피스톤": "sticky_piston",
    "레일": "rail",
    "파워레일": "powered_rail",
    "조명": "lantern",
    "랜턴": "lantern",
    "모닥불": "campfire",
    # ── 도구·무기 ─────────────────────────────────────────────
    "철검": "iron_sword",
    "다이아검": "diamond_sword",
    "네더라이트검": "netherite_sword",
    "철곡괭이": "iron_pickaxe",
    "다이아곡괭이": "diamond_pickaxe",
    "네더라이트곡괭이": "netherite_pickaxe",
    "철도끼": "iron_axe",
    "다이아도끼": "diamond_axe",
    "철삽": "iron_shovel",
    "다이아삽": "diamond_shovel",
    "철괭이": "iron_hoe",
    "활": "bow",
    "석궁": "crossbow",
    "화살": "arrow",
    "낚싯대": "fishing_rod",
    "라이터": "flint_and_steel",
    "부시": "flint_and_steel",
    "가위": "shears",
    "방패": "shield",
    "삼지창": "trident",
    "겉날개": "elytra",
    "엘리트라": "elytra",
    "안장": "saddle",
    "이름표": "name_tag",
    "나침반": "compass",
    "시계": "clock",
    "지도": "map",
    "망원경": "spyglass",
    # ── 방어구 ────────────────────────────────────────────────
    "철투구": "iron_helmet",
    "철흉갑": "iron_chestplate",
    "철레깅스": "iron_leggings",
    "철부츠": "iron_boots",
    "다이아투구": "diamond_helmet",
    "다이아흉갑": "diamond_chestplate",
    "다이아레깅스": "diamond_leggings",
    "다이아부츠": "diamond_boots",
    "네더라이트흉갑": "netherite_chestplate",
    # ── 음식 ─────────────────────────────────────────────────
    "사과": "apple",
    "황금사과": "golden_apple",
    "금사과": "golden_apple",
    "빵": "bread",
    "스테이크": "cooked_beef",
    "익힌소고기": "cooked_beef",
    "익힌돼지고기": "cooked_porkchop",
    "익힌닭고기": "cooked_chicken",
    "익힌대구": "cooked_cod",
    "익힌연어": "cooked_salmon",
    "당근": "carrot",
    "감자": "potato",
    "구운감자": "baked_potato",
    "케이크": "cake",
    "쿠키": "cookie",
    "수박": "melon_slice",
    "호박파이": "pumpkin_pie",
    "밀": "wheat",
    "밀씨앗": "wheat_seeds",
    "설탕": "sugar",
    "달걀": "egg",
    "우유": "milk_bucket",
    "우유양동이": "milk_bucket",
    # ── 기타 ─────────────────────────────────────────────────
    "양동이": "bucket",
    "물양동이": "water_bucket",
    "용암양동이": "lava_bucket",
    "경험치병": "experience_bottle",
    "토템": "totem_of_undying",
    "불사의토템": "totem_of_undying",
    "셜커껍데기": "shulker_shell",
    "광산수레": "minecart",
    "마인카트": "minecart",
    "배": "oak_boat",
    "보트": "oak_boat",
    "폭죽": "firework_rocket",
    "불꽃놀이로켓": "firework_rocket",
    "유리병": "glass_bottle",
}

# 오타 추천에 쓰는 후보 목록. 별칭의 값(영어 ID)을 기본으로 하고, 별칭은
# 없지만 자주 검색될 만한 ID를 몇 개 더 얹습니다.
KNOWN_ITEM_IDS = sorted(
    set(ITEM_ALIASES.values())
    | {
        "iron_sword", "iron_pickaxe", "golden_carrot", "cobblestone",
        "oak_sapling", "spruce_log", "birch_log", "netherite_block",
        "copper_block", "bookshelf", "brewing_stand", "cauldron",
        "hopper", "dropper", "dispenser", "redstone_torch", "repeater",
        "comparator", "slime_block", "honey_block", "scaffolding",
        "netherite_pickaxe", "netherite_axe", "netherite_shovel",
        "enchanted_golden_apple", "chorus_fruit", "shulker_box",
    }
)
